### ISSUE TITLE
Hardware used to train

### ISSUE THREAD

**Issue by nanometer34688** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#9]
I've read through the Google research paper and there isn't anything the suggests what kind of hardware they are using.

What are you using to train this repo on?

 I currently have 2 GTX 1070s and am worried that might not be enough

**Comment by JusperLee** [comment]
I used 8 GTX 1080Ti

Oli <notifications@github.com> 于2020年4月1日周三 下午6:02写道：

**Comment by nanometer34688** [comment]
Thanks for the quick reply. 

Roughly how long do you train on them?

Does your model output 2 distinct spectograms that are audible? Previously when I have tried it, It just sounds like noise

**Comment by JusperLee** [comment]
I did not use all the datasets as training. Only 5% of the dataset was
taken for training. I don't think this model can get good results, because
the sound of two people cannot be separated through experiments. I will
announce a baseline of a new audiovisual model recently. This model will
solve the problem of large data set training very well, and can perfectly
separate the voices of different people in the video.

nanometer <notifications@github.com> 于2020年4月1日周三 下午6:52写道：
